language: node_js
node_js:
  - "node"
cache:
  directories:
  - node_modules
script:
- yarn build
- yarn test
deploy:
  provider: script
  skip_cleanup: true
  script: yarn deploy
notifications:
  slack:
    on_success: change
    on_failure: change
