language: node_js
node_js:
  - "10"
cache:
  directories:
    - node_modules
script:
  - yarn build
  - yarn test
before_deploy:
  - git tag "$(date +'%Y%m%d-%H%M%S')-$(git log --format=%h -1)"
  - cd build
  - tar -zcf sqlite.tar.gz metabase.sqlite
  - tar -zcf postgres.tar.gz kodetre_postgres.json
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file:
    - build/sqlite.tar.gz
    - build/postgres.tar.gz
  on:
    repo: Artsdatabanken/kverna
  skip_cleanup: true
notifications:
  slack:
    on_success: change
    on_failure: change
